# Generated by Django 5.1.5 on 2025-03-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
