# Generated by Django 5.1.5 on 2025-03-16 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0004_review_country_review_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
