# Generated by Django 5.1.5 on 2025-03-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0006_order_orderform_ordermessage_orderattachment_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
