# Generated by Django 5.1.5 on 2025-03-20 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0008_streamasset_userasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.ImageField(blank=True, upload_to='stream_assets/media/')),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='STORE.streamasset')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('static', 'Static'), ('animated', 'Animated'), ('video', 'Video')], max_length=20)),
                ('file_path', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='STORE.streamasset')),
            ],
        ),
    ]
