# Generated by Django 5.1.5 on 2025-03-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0009_assetmedia_assetversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
