# Generated by Django 5.1.5 on 2025-03-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0011_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
