# Generated by Django 5.1.5 on 2025-04-06 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0013_notificationrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('referrer', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='STORE.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['product'], name='STORE_pagev_product_65886e_idx'), models.Index(fields=['url'], name='STORE_pagev_url_a285ab_idx'), models.Index(fields=['timestamp'], name='STORE_pagev_timesta_a697ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('interaction_type', models.CharField(choices=[('view', 'Page View'), ('click', 'Click'), ('purchase', 'Purchase'), ('review', 'Review'), ('message', 'Message')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='STORE.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['product', 'interaction_type'], name='STORE_produ_product_c72e2b_idx'), models.Index(fields=['timestamp'], name='STORE_produ_timesta_16fd62_idx')],
            },
        ),
    ]
