# Generated by Django 5.1.5 on 2025-04-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0015_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='fiverr_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_fiverr',
            field=models.BooleanField(default=False),
        ),
    ]
