# Generated by Django 5.1.5 on 2025-04-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STORE', '0017_discountcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='discountcode',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin Generated'), ('minesweeper', 'Minesweeper Win'), ('other', 'Other')], default='admin', max_length=20),
        ),
    ]
