# Generated by Django 4.2.18 on 2025-11-04 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FUZEOBS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuzeobsprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FuzeOBSQuickstart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuzeOBSChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('messages', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('template_use', 'Template Use'), ('profile_create', 'Profile Create'), ('benchmark', 'Benchmark')], max_length=50)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('app', 'Desktop App')], default='app', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'activity_type'], name='FUZEOBS_use_user_id_a07591_idx'), models.Index(fields=['timestamp'], name='FUZEOBS_use_timesta_4cab73_idx'), models.Index(fields=['source'], name='FUZEOBS_use_source_2e3b3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TierChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_tier', models.CharField(max_length=20)),
                ('to_tier', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='FUZEOBS_tie_user_id_6e7f0c_idx'), models.Index(fields=['timestamp'], name='FUZEOBS_tie_timesta_65c747_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuzeOBSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('lifetime', 'Lifetime')], default='free', max_length=20)),
                ('registration_source', models.CharField(default='fuzeobs', max_length=20)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('last_app_login', models.DateTimeField(blank=True, null=True)),
                ('total_app_sessions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tier'], name='FUZEOBS_fuz_tier_78e36d_idx'), models.Index(fields=['registration_source'], name='FUZEOBS_fuz_registr_f79edb_idx'), models.Index(fields=['last_app_login'], name='FUZEOBS_fuz_last_ap_697978_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_count', models.IntegerField(default=1)),
                ('tokens_used', models.IntegerField(default=0)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('request_type', models.CharField(choices=[('chat', 'Chat'), ('benchmark', 'Benchmark Analysis')], default='chat', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.FloatField(null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'timestamp'], name='FUZEOBS_aiu_user_id_6c9ca4_idx'), models.Index(fields=['timestamp'], name='FUZEOBS_aiu_timesta_28f532_idx'), models.Index(fields=['request_type'], name='FUZEOBS_aiu_request_e61383_idx'), models.Index(fields=['success'], name='FUZEOBS_aiu_success_6c5ffd_idx')],
            },
        ),
    ]
