# Generated by Django 4.2.18 on 2025-11-04 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FUZEOBS', '0002_alter_fuzeobsprofile_user_fuzeobsquickstart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('mac', 'Mac'), ('linux', 'Linux')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['platform', 'timestamp'], name='FUZEOBS_dow_platfor_148ab6_idx'), models.Index(fields=['timestamp'], name='FUZEOBS_dow_timesta_1ae656_idx')],
            },
        ),
    ]
