# Generated by Django 4.2.18 on 2025-11-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0002_magiclogintoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MagicLoginToken',
        ),
    ]
