# Generated by Django 4.2.18 on 2025-11-12 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FUZEOBS', '0003_delete_magiclogintoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('alert_box', 'Alert Box'), ('chat_box', 'Chat Box'), ('event_list', 'Event List'), ('goal_bar', 'Goal Bar')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('gcs_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
