# Generated by Django 4.2.18 on 2025-11-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0005_medialibrary_widgetevent_platformconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetconfig',
            name='token',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AddIndex(
            model_name='widgetconfig',
            index=models.Index(fields=['token'], name='FUZEOBS_wid_token_dcccdf_idx'),
        ),
    ]
