# Generated by Django 4.2.18 on 2025-11-17 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FUZEOBS', '0006_widgetconfig_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetconfig',
            name='platform',
            field=models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('kick', 'Kick')], default='twitch', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='widgetconfig',
            unique_together={('user', 'widget_type', 'platform')},
        ),
    ]
