# Generated by Django 4.2.18 on 2025-11-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0007_widgetconfig_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconnection',
            name='platform_user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
