# Generated by Django 4.2.18 on 2025-11-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0008_platformconnection_platform_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconnection',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
