# Generated by Django 4.2.18 on 2025-11-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0009_platformconnection_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconnection',
            name='platform',
            field=models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('kick', 'Kick'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('all', 'All Platforms')], max_length=20),
        ),
        migrations.AlterField(
            model_name='widgetconfig',
            name='platform',
            field=models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('kick', 'Kick'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('all', 'All Platforms')], max_length=20),
        ),
    ]
