# Generated by Django 4.2.18 on 2025-11-26 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FUZEOBS', '0010_alter_platformconnection_platform_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='widgetconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='goal_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='widgetconfig',
            unique_together={('user', 'widget_type', 'platform', 'goal_type')},
        ),
    ]
