# Generated by Django 4.2.18 on 2025-11-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0011_alter_widgetconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetconfig',
            name='goal_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='widgetconfig',
            name='widget_type',
            field=models.CharField(choices=[('alert_box', 'Alert Box'), ('chat_box', 'Chat Box'), ('event_list', 'Event List'), ('goal_bar', 'Goal Bar'), ('labels', 'Labels')], max_length=20),
        ),
    ]
