# Generated by Django 4.2.18 on 2025-11-27 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FUZEOBS', '0012_alter_widgetconfig_goal_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelSessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', models.CharField(max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'label_type'], name='FUZEOBS_lab_user_id_d688f9_idx')],
                'unique_together': {('user', 'label_type')},
            },
        ),
    ]
