# Generated by Django 4.2.18 on 2025-11-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0013_labelsessiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetconfig',
            name='widget_type',
            field=models.CharField(choices=[('alert_box', 'Alert Box'), ('chat_box', 'Chat Box'), ('event_list', 'Event List'), ('goal_bar', 'Goal Bar'), ('labels', 'Labels'), ('viewer_count', 'Viewer Count')], max_length=20),
        ),
    ]
