# Generated by Django 4.2.18 on 2025-12-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0014_alter_widgetconfig_widget_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetconfig',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='widgetconfig',
            name='widget_type',
            field=models.CharField(choices=[('alert_box', 'Alert Box'), ('chat_box', 'Chat Box'), ('event_list', 'Event List'), ('goal_bar', 'Goal Bar'), ('labels', 'Labels'), ('viewer_count', 'Viewer Count'), ('sponsor_banner', 'Sponsor Banner')], max_length=20),
        ),
    ]
