# Generated by Django 4.2.18 on 2025-12-08 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FUZEOBS', '0015_widgetconfig_enabled_alter_widgetconfig_widget_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254)),
                ('paypal_merchant_id', models.CharField(blank=True, max_length=100)),
                ('oauth_state', models.CharField(blank=True, max_length=64)),
                ('min_amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('suggested_amounts', models.JSONField(default=list)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('page_title', models.CharField(default='Support My Stream!', max_length=200)),
                ('page_message', models.TextField(blank=True, default='Thanks for supporting the stream!')),
                ('show_recent_donations', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['donation_token'], name='FUZEOBS_don_donatio_c6053a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_order_id', models.CharField(max_length=100, unique=True)),
                ('paypal_capture_id', models.CharField(blank=True, max_length=100)),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuzeobs_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['streamer', 'status'], name='FUZEOBS_don_streame_d054d1_idx'), models.Index(fields=['paypal_order_id'], name='FUZEOBS_don_paypal__bf2ab2_idx'), models.Index(fields=['created_at'], name='FUZEOBS_don_created_adf896_idx')],
            },
        ),
    ]
