# Generated by Django 4.2.18 on 2025-12-12 23:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0017_fuzeobssubscription_fuzeobspurchase'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='donation',
            name='FUZEOBS_don_paypal__bf2ab2_idx',
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='FUZEOBS_don_created_adf896_idx',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='paypal_capture_id',
            new_name='stripe_payment_intent',
        ),
        migrations.RenameField(
            model_name='donationsettings',
            old_name='paypal_merchant_id',
            new_name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='paypal_order_id',
        ),
        migrations.RemoveField(
            model_name='donationsettings',
            name='oauth_state',
        ),
        migrations.RemoveField(
            model_name='donationsettings',
            name='paypal_email',
        ),
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['stripe_payment_intent'], name='FUZEOBS_don_stripe__4d0e63_idx'),
        ),
    ]
