# Generated by Django 4.2.18 on 2025-12-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0017_fuzeobssubscription_fuzeobspurchase'),
    ]

    operations = [
        # Remove old indexes
        migrations.RemoveIndex(
            model_name='donation',
            name='FUZEOBS_don_paypal__bf2ab2_idx',
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='FUZEOBS_don_created_adf896_idx',
        ),
        
        # Donation: Remove PayPal fields, add Stripe field
        migrations.RemoveField(
            model_name='donation',
            name='paypal_order_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='paypal_capture_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='donation',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        
        # DonationSettings: Remove PayPal fields, add Stripe field
        migrations.RemoveField(
            model_name='donationsettings',
            name='paypal_email',
        ),
        migrations.RemoveField(
            model_name='donationsettings',
            name='paypal_merchant_id',
        ),
        migrations.RemoveField(
            model_name='donationsettings',
            name='oauth_state',
        ),
        migrations.AddField(
            model_name='donationsettings',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]