# Generated by Django 4.2.18 on 2025-12-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0018_remove_donation_fuzeobs_don_paypal__bf2ab2_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationsettings',
            old_name='stripe_account_id',
            new_name='paypal_merchant_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='stripe_payment_intent',
        ),
        migrations.AddField(
            model_name='donation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='paypal_capture_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='paypal_order_id',
            field=models.CharField(default='legacy', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationsettings',
            name='oauth_state',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='donationsettings',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['paypal_order_id'], name='FUZEOBS_don_paypal__bf2ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['created_at'], name='FUZEOBS_don_created_adf896_idx'),
        ),
    ]
