# Generated by Django 4.2.18 on 2025-12-26 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FUZEOBS', '0019_rename_stripe_account_id_donationsettings_paypal_merchant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuzeOBSPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=50)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['page', 'timestamp'], name='FUZEOBS_fuz_page_8a9781_idx')],
            },
        ),
    ]
