# Generated by Django 4.2.18 on 2026-01-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0020_fuzeobspageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationsettings',
            name='oauth_state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
