# Generated by Django 4.2.18 on 2026-02-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0021_alter_donationsettings_oauth_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationsettings',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
