# Generated by Django 4.2.18 on 2026-02-04 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FUZEOBS', '0022_donationsettings_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuzeOBSReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('kick', 'Kick'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('other', 'Other')], max_length=20)),
                ('rating', models.IntegerField()),
                ('review', models.TextField(max_length=300)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='fuzeobsreview',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_review'),
        ),
    ]
