# Generated by Django 4.2.18 on 2026-02-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0024_streamcountdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamcountdown',
            name='schedule_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='streamcountdown',
            name='schedule_time',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='streamcountdown',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
