# Generated by Django 4.2.18 on 2026-02-08 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FUZEOBS', '0025_streamcountdown_schedule_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('title', models.CharField(default='Untitled', max_length=300)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('views', models.IntegerField(default=0)),
                ('vod_url', models.URLField(blank=True, max_length=500)),
                ('clips', models.IntegerField(default=0)),
                ('stream_id', models.CharField(blank=True, max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'platform'], name='FUZEOBS_str_user_id_713ebe_idx')],
            },
        ),
    ]
