# Generated by Django 4.2.18 on 2026-02-08 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0026_streamrecap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StreamRecap',
        ),
    ]
