# Generated by Django 4.2.18 on 2026-02-12 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FUZEOBS', '0027_delete_streamrecap'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('duo', 'Duo Queue'), ('group', 'Group Stream'), ('podcast', 'Podcast / Talk Show'), ('tournament', 'Tournament'), ('charity', 'Charity Event'), ('creative', 'Creative Collab'), ('irl', 'IRL Stream'), ('other', 'Other')], max_length=20)),
                ('platforms', models.JSONField(default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('collab_size', models.CharField(choices=[('duo', 'Duo (2)'), ('small', 'Small Group (3-5)'), ('large', 'Large Group (6+)'), ('any', 'Any Size')], default='duo', max_length=10)),
                ('availability', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('closed', 'Closed')], default='open', max_length=10)),
                ('interested_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollabInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='FUZEOBS.collabpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='collabpost',
            index=models.Index(fields=['status', '-created_at'], name='FUZEOBS_col_status_e6ebec_idx'),
        ),
        migrations.AddIndex(
            model_name='collabpost',
            index=models.Index(fields=['user', '-created_at'], name='FUZEOBS_col_user_id_16db76_idx'),
        ),
        migrations.AddIndex(
            model_name='collabpost',
            index=models.Index(fields=['category'], name='FUZEOBS_col_categor_770306_idx'),
        ),
        migrations.AddIndex(
            model_name='collabinterest',
            index=models.Index(fields=['post', 'user'], name='FUZEOBS_col_post_id_88c5a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collabinterest',
            unique_together={('post', 'user')},
        ),
    ]
