# Generated by Django 4.2.18 on 2026-02-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0028_collabpost_collabinterest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabpost',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='collabpost',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
