# Generated by Django 4.2.18 on 2026-02-14 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FUZEOBS', '0029_alter_collabpost_description_alter_collabpost_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opted_in', models.BooleanField(default=True)),
                ('total_stream_minutes', models.IntegerField(default=0)),
                ('weekly_stream_minutes', models.IntegerField(default=0)),
                ('monthly_stream_minutes', models.IntegerField(default=0)),
                ('previous_rank', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['-total_stream_minutes'], name='FUZEOBS_lea_total_s_453b82_idx'), models.Index(fields=['-weekly_stream_minutes'], name='FUZEOBS_lea_weekly__bc6292_idx'), models.Index(fields=['-monthly_stream_minutes'], name='FUZEOBS_lea_monthly_4a3b3d_idx'), models.Index(fields=['opted_in'], name='FUZEOBS_lea_opted_i_e07e45_idx')],
            },
        ),
    ]
