# Generated by Django 4.2.18 on 2026-02-19 03:11

import FUZEOBS.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0030_leaderboardentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconnection',
            name='access_token',
            field=FUZEOBS.models.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='platformconnection',
            name='refresh_token',
            field=FUZEOBS.models.EncryptedTextField(blank=True),
        ),
    ]
