# Generated by Django 4.2.18 on 2026-02-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0032_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabpost',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='collabpost',
            index=models.Index(fields=['status', 'expires_at'], name='FUZEOBS_col_status_451e0c_idx'),
        ),
    ]
