# Generated by Django 4.2.18 on 2026-03-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FUZEOBS', '0033_collabpost_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=32)),
                ('session_id', models.CharField(db_index=True, max_length=32)),
                ('event', models.CharField(db_index=True, max_length=100)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('app_version', models.CharField(blank=True, default='', max_length=20)),
                ('os_name', models.CharField(blank=True, default='', max_length=20)),
                ('os_version', models.CharField(blank=True, default='', max_length=50)),
                ('client_timestamp', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'created_at'], name='FUZEOBS_tel_event_63113f_idx'), models.Index(fields=['device_id', 'created_at'], name='FUZEOBS_tel_device__dbaf65_idx')],
            },
        ),
    ]
