# Generated by Django 4.2.18 on 2026-03-04 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FUZEOBS', '0034_telemetryevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('creator_name', models.CharField(max_length=100)),
                ('creator_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Creator Code',
            },
        ),
        migrations.CreateModel(
            name='CreatorCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('pro', 'Pro Monthly'), ('3month', '3-Month Pro'), ('lifetime', 'Lifetime')], max_length=20)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creator_earnings', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stripe_session_id', models.CharField(max_length=200, unique=True)),
                ('paid_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='FUZEOBS.creatorcode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creator Code Usage',
                'ordering': ['-created_at'],
            },
        ),
    ]
