# Generated by Django 4.2.18 on 2026-03-04 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FUZEOBS', '0035_creatorcode_creatorcodeusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorcode',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
