"""
Django settings for mywebsite project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from django.urls import reverse_lazy
import os
from dotenv import load_dotenv
import logging

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

# Load environment variables from .env file
load_dotenv(Path(__file__).resolve().parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []
ALLOWED_HOSTS = ['bomby.us', 'www.bomby.us', 'bomby-799218251279.us-central1.run.app', 'localhost', '127.0.0.1']
CSRF_TRUSTED_ORIGINS = ['https://bomby.us', 'http://bomby.us', 'https://bomby-799218251279.us-central1.run.app']

# Security Settings only set in production
SECURE_SSL_REDIRECT = not DEBUG and not os.environ.get('DISABLE_SSL_REDIRECT')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookie Domains only set in production
if not DEBUG:
    CSRF_COOKIE_DOMAIN = '.bomby.us'
    SESSION_COOKIE_DOMAIN = '.bomby.us'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'MAIN',
    'ACCOUNTS',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'PORTFOLIO',
    'STORE',
    'storages',
    'FUZEOBS',
    'channels',
]

ASGI_APPLICATION = 'mywebsite.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

AUTHENTICATION_BACKENDS = [
    # Existing backend
    'django.contrib.auth.backends.ModelBackend',
    
    # Add allauth backend
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Google Auth settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID'),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET'),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# AllAuth settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_ADAPTER = 'ACCOUNTS.adapters.CustomSocialAccountAdapter'

# Add site ID
SITE_ID = 1

MIDDLEWARE = [
    'FUZEOBS.middleware.CorsOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'STORE.middleware.AnalyticsMiddleware',
]

ROOT_URLCONF = 'mywebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'MAIN.context_processors.announcement_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'mywebsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', '/cloudsql/premium-botany-453018-a0:us-central1:bomby-database'),
        'PORT': '5432',
    }
}

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'fuzeobs-cache',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Whitenoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

WHITENOISE_MIMETYPES = {
    '.css': 'text/css',
    '.js': 'application/javascript',
    '.html': 'text/html',
    '.jpg': 'image/jpeg',
    '.png': 'image/png',
    '.svg': 'image/svg+xml',
    '.webmanifest': 'application/manifest+json',
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

## ADMIN PANEL CODE
ADMIN_VERIFICATION_CODE = os.environ.get('ADMIN_VERIFICATION_CODE')

## EMAIL SETTINGS SMTP
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'sebetvbusiness@gmail.com')
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER')

## LOGIN SETTINGS
AUTH_USER_MODEL = 'ACCOUNTS.User'
LOGIN_URL = 'ACCOUNTS:login'
LOGIN_REDIRECT_URL = reverse_lazy('ACCOUNTS:account')
LOGOUT_REDIRECT_URL = 'MAIN:home'

## AWS SETTINGS
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_REGION = os.environ.get('AWS_REGION', 'us-east-1')

# AWS Rekognition
ENABLE_IMAGE_MODERATION = os.environ.get('ENABLE_IMAGE_MODERATION')
IMAGE_MODERATION_CONFIDENCE_THRESHOLD = os.environ.get('IMAGE_MODERATION_CONFIDENCE_THRESHOLD')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# For Cloud Run with mounted bucket
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# For Cloud Run with mounted bucket
if os.environ.get('K_SERVICE'):  # This env var is present in Cloud Run
    # Path where the bucket is mounted
    GS_MEDIA_BUCKET_PATH = '/app/media'
    # Set media root to the mount point
    MEDIA_ROOT = GS_MEDIA_BUCKET_PATH

# Payment Details
PAYPAL_CLIENT_ID = os.environ.get('PAYPAL_CLIENT_ID')
PAYPAL_SECRET = os.environ.get('PAYPAL_SECRET')
PAYPAL_SANDBOX_MODE = False
PAYPAL_MODE = 'live'

# Allow PayPal popups to work properly
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

# Comprehensive CSP that allows PayPal integration
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = (
    "'self'", 
    "'unsafe-inline'", 
    "'unsafe-eval'",
    "https://*.paypal.com", 
    "https://*.paypalobjects.com",
    "https://*.google.com"
)
CSP_STYLE_SRC = (
    "'self'", 
    "'unsafe-inline'",
    "https://cdnjs.cloudflare.com",
    "https://*.paypal.com", 
    "https://*.paypalobjects.com",
    "https://unpkg.com",
    "https://maxcdn.bootstrapcdn.com"
)
CSP_CONNECT_SRC = (
    "'self'",
    "https://*.paypal.com",
    "https://*.paypal.cn",
    "https://*.paypalobjects.com",
    "https://objects.paypal.cn",
    "https://192.55.233.1",
    "https://*.google.com",
    "https://www.google.com",
    "https://browser-intake-us5-datadoghq.com",
    "https://*.qualtrics.com"
)
CSP_FRAME_SRC = (
    "'self'",
    "https://*.paypal.com",
    "https://*.google.com"
)
CSP_IMG_SRC = (
    "'self'",
    "data:",
    "https://*.paypal.com",
    "https://*.paypalobjects.com",
    "https://*.google.com"
)
CSP_FONT_SRC = (
    "'self'",
    "data:",
    "https://cdnjs.cloudflare.com",
    "https://*.paypal.com",
    "https://*.paypalobjects.com",
    "https://fonts.gstatic.com",
    "https://unpkg.com",
    "https://maxcdn.bootstrapcdn.com"
)

# FuzeOBS Secret Key
FUZEOBS_SECRET_KEY = os.environ.get('FUZEOBS_SECRET_KEY')

# Twitch Keys
TWITCH_CLIENT_ID = os.environ.get('TWITCH_CLIENT_ID')
TWITCH_CLIENT_SECRET = os.environ.get('TWITCH_CLIENT_SECRET')
TWITCH_WEBHOOK_SECRET = os.environ.get('TWITCH_WEBHOOK_SECRET')