# Generated by Django 4.2.18 on 2025-12-08 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fuzeobs_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fuzeobs_lifetime',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fuzeobs_subscription_end',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fuzeobs_subscription_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
    ]
