# Generated by Django 4.2.18 on 2026-02-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0005_sync_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fuzeobs_token_version',
            field=models.IntegerField(default=0),
        ),
    ]
