# Generated by Django 5.1.5 on 2025-02-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0005_rename_x_link_user_twitter_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_promo_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
