# Generated by Django 5.1.5 on 2025-02-28 05:49

import ACCOUNTS.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0008_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[ACCOUNTS.validators.validate_clean_content]),
        ),
    ]
