# Generated by Django 5.1.5 on 2025-03-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0009_alter_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='youtube_link',
            new_name='youtube_link_1',
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_link_2',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
