# Generated by Django 5.1.5 on 2025-03-07 18:33

import ACCOUNTS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0014_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', validators=[ACCOUNTS.models.validate_image_size, ACCOUNTS.models.validate_image_dimensions]),
        ),
    ]
