# Generated by Django 5.1.5 on 2025-03-09 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0016_user_firebase_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='ACCOUNTS_user',
        ),
    ]
