# Generated by Django 5.1.5 on 2025-03-26 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0020_messagenotification'),
        ('STORE', '0010_order_is_paid_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='related_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='STORE.product'),
        ),
    ]
