# Generated by Django 4.2.18 on 2025-10-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0021_message_related_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fuzeobs_ai_usage_monthly',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='fuzeobs_tier',
            field=models.CharField(default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='fuzeobs_usage_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
