# Generated by Django 4.2.18 on 2025-10-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0022_user_fuzeobs_ai_usage_monthly_user_fuzeobs_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fuzeobs_chat_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
