# Generated by Django 4.2.18 on 2025-10-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0023_user_fuzeobs_chat_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quickstart_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
