# Generated by Django 4.2.18 on 2025-11-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0024_user_quickstart_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fuzeobs_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='fuzeobs_app_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='fuzeobs_first_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fuzeobs_last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fuzeobs_total_sessions',
            field=models.IntegerField(default=0),
        ),
    ]
