# Generated by Django 5.1.5 on 2025-09-03 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminCodeVerification',
        ),
    ]
