# Generated by Django 5.1.5 on 2025-02-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0002_user_profile_picture_user_twitch_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('SUPPORTER', 'Supporter'), ('CLIENT', 'Client'), ('ADMIN', 'Admin')], default='MEMBER', max_length=10),
        ),
    ]
