# Generated by Django 5.1.5 on 2025-02-28 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0004_user_instagram_link_user_kick_link_user_x_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='x_link',
            new_name='twitter_link',
        ),
    ]
