# Generated by Django 5.1.5 on 2025-02-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNTS', '0006_user__promo_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
