# Generated by Django 4.2.18 on 2026-03-19 16:54

import FUZE.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreatorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('creator_name', models.CharField(max_length=100)),
                ('creator_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creator Code',
            },
        ),
        migrations.CreateModel(
            name='WidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('alert_box', 'Alert Box'), ('chat_box', 'Chat Box'), ('event_list', 'Event List'), ('goal_bar', 'Goal Bar'), ('labels', 'Labels'), ('viewer_count', 'Viewer Count'), ('sponsor_banner', 'Sponsor Banner')], max_length=20)),
                ('platform', models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('kick', 'Kick'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('all', 'All Platforms')], max_length=20)),
                ('goal_type', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('token', models.CharField(blank=True, max_length=128, unique=True)),
                ('gcs_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('template_use', 'Template Use'), ('profile_create', 'Profile Create'), ('benchmark', 'Benchmark')], max_length=50)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('app', 'Desktop App')], default='app', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TierChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_tier', models.CharField(max_length=20)),
                ('to_tier', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=32)),
                ('session_id', models.CharField(db_index=True, max_length=32)),
                ('event', models.CharField(db_index=True, max_length=100)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('app_version', models.CharField(blank=True, default='', max_length=20)),
                ('os_name', models.CharField(blank=True, default='', max_length=20)),
                ('os_version', models.CharField(blank=True, default='', max_length=50)),
                ('client_timestamp', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'created_at'], name='FUZE_teleme_event_59c7c3_idx'), models.Index(fields=['device_id', 'created_at'], name='FUZE_teleme_device__c1b03f_idx')],
            },
        ),
        migrations.CreateModel(
            name='StreamCountdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('platforms', models.JSONField(default=list)),
                ('schedule_days', models.JSONField(blank=True, default=list)),
                ('schedule_time', models.CharField(blank=True, default='', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('kick', 'Kick'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('all', 'All Platforms')], max_length=20)),
                ('platform_username', models.CharField(max_length=100)),
                ('access_token', FUZE.models.EncryptedTextField()),
                ('refresh_token', FUZE.models.EncryptedTextField(blank=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('platform_user_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('sound', 'Sound'), ('video', 'Video')], max_length=10)),
                ('file_url', models.URLField()),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opted_in', models.BooleanField(default=True)),
                ('total_stream_minutes', models.IntegerField(default=0)),
                ('weekly_stream_minutes', models.IntegerField(default=0)),
                ('monthly_stream_minutes', models.IntegerField(default=0)),
                ('previous_rank', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabelSessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', models.CharField(max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuzeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('lifetime', 'Lifetime')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuze_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuzeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('kick', 'Kick'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('other', 'Other')], max_length=20)),
                ('rating', models.IntegerField()),
                ('review', models.TextField(max_length=300)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuzeQuickstart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuzePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuze_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuzeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FuzePageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=50)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuzeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('messages', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('mac', 'Mac'), ('linux', 'Linux')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254)),
                ('paypal_merchant_id', models.CharField(blank=True, max_length=100)),
                ('oauth_state', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('min_amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('suggested_amounts', models.JSONField(default=list)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('page_title', models.CharField(default='Support My Stream!', max_length=200)),
                ('page_message', models.TextField(blank=True, default='Thanks for supporting the stream!')),
                ('show_recent_donations', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_order_id', models.CharField(max_length=100, unique=True)),
                ('paypal_capture_id', models.CharField(blank=True, max_length=100)),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuze_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreatorCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('pro', 'Pro Monthly'), ('3month', '3-Month Pro'), ('lifetime', 'Lifetime')], max_length=20)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creator_earnings', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stripe_session_id', models.CharField(max_length=200, unique=True)),
                ('paid_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='FUZE.creatorcode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creator Code Usage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollabPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('category', models.CharField(choices=[('duo', 'Duo Queue'), ('group', 'Group Stream'), ('podcast', 'Podcast / Talk Show'), ('tournament', 'Tournament'), ('charity', 'Charity Event'), ('creative', 'Creative Collab'), ('irl', 'IRL Stream'), ('other', 'Other')], max_length=20)),
                ('platforms', models.JSONField(default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('collab_size', models.CharField(choices=[('duo', 'Duo (2)'), ('small', 'Small Group (3-5)'), ('large', 'Large Group (6+)'), ('any', 'Any Size')], default='duo', max_length=10)),
                ('availability', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('closed', 'Closed')], default='open', max_length=10)),
                ('interested_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollabInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='FUZE.collabpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tier', models.CharField(default='free', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('message_count', models.IntegerField(default=1)),
                ('tokens_used', models.IntegerField(default=0)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('request_type', models.CharField(choices=[('chat', 'Chat'), ('benchmark', 'Benchmark Analysis')], default='chat', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.FloatField(null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_ping', models.DateTimeField(auto_now=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FUZE.widgetconfig')),
            ],
            options={
                'unique_together': {('widget', 'event_type', 'platform')},
            },
        ),
        migrations.AddIndex(
            model_name='widgetconfig',
            index=models.Index(fields=['token'], name='FUZE_widget_token_c1150e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='widgetconfig',
            unique_together={('user', 'widget_type', 'platform', 'goal_type')},
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_type'], name='FUZE_userac_user_id_a45709_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['timestamp'], name='FUZE_userac_timesta_267315_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['source'], name='FUZE_userac_source_3a33c7_idx'),
        ),
        migrations.AddIndex(
            model_name='tierchange',
            index=models.Index(fields=['user', 'timestamp'], name='FUZE_tierch_user_id_a74c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='tierchange',
            index=models.Index(fields=['timestamp'], name='FUZE_tierch_timesta_a58376_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platformconnection',
            unique_together={('user', 'platform')},
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['-total_stream_minutes'], name='FUZE_leader_total_s_734f08_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['-weekly_stream_minutes'], name='FUZE_leader_weekly__e6d74c_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['-monthly_stream_minutes'], name='FUZE_leader_monthly_e63cad_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['opted_in'], name='FUZE_leader_opted_i_ceb3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='labelsessiondata',
            index=models.Index(fields=['user', 'label_type'], name='FUZE_labels_user_id_b5a59d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labelsessiondata',
            unique_together={('user', 'label_type')},
        ),
        migrations.AddConstraint(
            model_name='fuzereview',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_review'),
        ),
        migrations.AddIndex(
            model_name='fuzepageview',
            index=models.Index(fields=['page', 'timestamp'], name='FUZE_fuzepa_page_bf935c_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadtracking',
            index=models.Index(fields=['platform', 'timestamp'], name='FUZE_downlo_platfor_46cf28_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadtracking',
            index=models.Index(fields=['timestamp'], name='FUZE_downlo_timesta_f924c7_idx'),
        ),
        migrations.AddIndex(
            model_name='donationsettings',
            index=models.Index(fields=['donation_token'], name='FUZE_donati_donatio_1e2bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['streamer', 'status'], name='FUZE_donati_streame_9176f7_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['paypal_order_id'], name='FUZE_donati_paypal__401cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['created_at'], name='FUZE_donati_created_4beb12_idx'),
        ),
        migrations.AddIndex(
            model_name='collabpost',
            index=models.Index(fields=['status', '-created_at'], name='FUZE_collab_status_2e9408_idx'),
        ),
        migrations.AddIndex(
            model_name='collabpost',
            index=models.Index(fields=['user', '-created_at'], name='FUZE_collab_user_id_94d45a_idx'),
        ),
        migrations.AddIndex(
            model_name='collabpost',
            index=models.Index(fields=['category'], name='FUZE_collab_categor_42815e_idx'),
        ),
        migrations.AddIndex(
            model_name='collabpost',
            index=models.Index(fields=['status', 'expires_at'], name='FUZE_collab_status_36b8d2_idx'),
        ),
        migrations.AddIndex(
            model_name='collabinterest',
            index=models.Index(fields=['post', 'user'], name='FUZE_collab_post_id_b60119_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collabinterest',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='aiusage',
            index=models.Index(fields=['user', 'timestamp'], name='FUZE_aiusag_user_id_61cd20_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusage',
            index=models.Index(fields=['timestamp'], name='FUZE_aiusag_timesta_325175_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusage',
            index=models.Index(fields=['request_type'], name='FUZE_aiusag_request_ae84a5_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusage',
            index=models.Index(fields=['success'], name='FUZE_aiusag_success_e6423c_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusage',
            index=models.Index(fields=['is_anonymous'], name='FUZE_aiusag_is_anon_ced8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='activesession',
            index=models.Index(fields=['last_ping', 'is_anonymous'], name='FUZE_active_last_pi_cca7de_idx'),
        ),
    ]
